# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authords',
            new_name='authors',
        ),
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 3, 17, 22, 43, 977885, tzinfo=utc), verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads/%Y/%m/%d/'),
        ),
    ]
